# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170316_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.IntegerField(choices=[(0, 'Started'), (1, 'Passed'), (2, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='select',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
