# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170301_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('RADIOBOX', 'Radiobox'), ('TEXT', 'Text'), ('CODE', 'Code')], default='CHECKBOX', max_length=9),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hash',
            field=models.CharField(default=quiz.models.hash_generate, max_length=8, unique=True, verbose_name='Hash'),
        ),
    ]
