# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170301_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='hash',
            field=models.CharField(default=quiz.models.hash_generate, editable=False, max_length=8, unique=True, verbose_name='Hash'),
        ),
    ]
