# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170317_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('RADIOBOX', 'Radiobox'), ('TEXT', 'Text'), ('CODE', 'Code')], default='CHECKBOX', max_length=9, verbose_name='Answer type'),
        ),
    ]
