# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170301_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkbox',
            name='alternative',
        ),
        migrations.RemoveField(
            model_name='radiobox',
            name='alternative',
        ),
        migrations.DeleteModel(
            name='Checkbox',
        ),
        migrations.DeleteModel(
            name='Radiobox',
        ),
    ]
