# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20170322_1153'),
        ('quiz', '0005_auto_20170322_1149'),
    ]

    operations = [
    ]
