# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20170301_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternative',
            options={'verbose_name': 'Alternative: Checkbox/radiobox', 'verbose_name_plural': 'Alternative: Checkboxes/radioboxes'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Alternative: Code', 'verbose_name_plural': 'Alternative: Codes'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Alternative: Text', 'verbose_name_plural': 'Alternative: Texts'},
        ),
        migrations.RemoveField(
            model_name='code',
            name='alternative',
        ),
        migrations.RemoveField(
            model_name='text',
            name='alternative',
        ),
        migrations.AddField(
            model_name='code',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='quiz.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='quiz.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='quiz.Question'),
        ),
    ]
