# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170301_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(choices=[('JAVASCRIPT', 'Javascript'), ('JAVA', 'Java'), ('PYTHON', 'Python')], default='JAVASCRIPT', max_length=9),
        ),
        migrations.AlterField(
            model_name='code',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='quiz.Question', unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='quiz.Question', unique=True),
        ),
    ]
