# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
    ]
