# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_question_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
