# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alternative_correct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alternative',
            new_name='Select',
        ),
        migrations.AlterModelOptions(
            name='select',
            options={'verbose_name': 'Alternative: Selects', 'verbose_name_plural': 'Alternative: Selects'},
        ),
    ]
