# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_question_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
