# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20170302_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='passed',
        ),
        migrations.AddField(
            model_name='attempt',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
