# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_attempt_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='Quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='quiz.Quiz'),
            preserve_default=False,
        ),
    ]
