# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20170302_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='Quiz',
            new_name='quiz',
        ),
    ]
