# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20170302_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
