# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_question_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts',
            field=models.IntegerField(default=3),
        ),
    ]
