# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20170304_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Syllabus'),
        ),
    ]
