# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_code_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='input',
            field=models.CharField(max_length=3000),
        ),
    ]
