# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20170305_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='solution',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='input_shown',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='input_usable',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
