# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20170305_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='start_code',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
