# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_code_start_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='exercise_number',
            field=models.IntegerField(default=1),
        ),
    ]
